import type { Product, ProductFilter } from './store'

export const filters: { label: string; value: ProductFilter }[] = [
  { label: 'All', value: 'all' },
  { label: 'Chains', value: 'chains' },
  { label: 'Bracelets', value: 'bracelets' },
  { label: 'Rings', value: 'rings' },
  { label: 'Earrings', value: 'earrings' },
  { label: 'Watches', value: 'watches' },
]

export const seedProducts: Product[] = [
  {
    id: 'ghost-tennis-chain',
    name: 'Ghost Tennis Chain',
    category: 'chains',
    price: 740,
    stock: 6,
    certification: 'GRA Certified',
    stone: 'VVS Moissanite',
    image:
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1200&q=92',
    description:
      'A clean white-fire tennis chain with a low-profile clasp and a streetwear-heavy shine.',
    drop: 'Vault Drop 01',
    finish: 'Rhodium white gold finish',
    certificateId: 'GRA-IV-001',
    certificateDate: 'May 2026',
    carat: '38 ct total weight',
    cut: 'Round brilliant',
    clarity: 'VVS simulated clarity',
    specs: ['5mm hand-set stones', 'Box clasp', '18 inch lay'],
    tags: ['gra certified', 'tennis chain', 'white gold', 'unisex'],
  },
  {
    id: 'arctic-tennis-bracelet',
    name: 'Arctic Tennis Bracelet',
    category: 'bracelets',
    price: 420,
    stock: 9,
    certification: 'GRA Certified',
    stone: 'D Color Moissanite',
    image:
      'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1200&q=92',
    description:
      'Hand-set stones, icy edge, and a barely-there box clasp made for daily flex.',
    drop: 'Daily Ice',
    finish: 'Polished white gold finish',
    certificateId: 'GRA-IV-014',
    certificateDate: 'May 2026',
    carat: '14 ct total weight',
    cut: 'Round brilliant',
    clarity: 'VVS simulated clarity',
    specs: ['4mm round stones', 'Hidden clasp', '7.5 inch fit'],
    tags: ['gra certified', 'bracelet', 'iced out', 'minimal'],
  },
  {
    id: 'vault-solitaire-ring',
    name: 'Vault Solitaire Ring',
    category: 'rings',
    price: 360,
    stock: 4,
    certification: 'GRA Certified',
    stone: 'Brilliant Moissanite',
    image:
      'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=92',
    description:
      'A sharp solitaire cut with a mirror-polished band and clean luxury presence.',
    drop: 'Private Setting',
    finish: 'Mirror polish band',
    certificateId: 'GRA-IV-021',
    certificateDate: 'May 2026',
    carat: '2 ct center stone',
    cut: 'Brilliant solitaire',
    clarity: 'D color moissanite',
    specs: ['Brilliant center stone', 'Low basket setting', 'Gift-ready box'],
    tags: ['gra certified', 'ring', 'solitaire', 'gift'],
  },
  {
    id: 'frostline-cuban-link',
    name: 'Frostline Cuban Link',
    category: 'chains',
    price: 680,
    stock: 3,
    certification: 'GRA Certified',
    stone: 'Moissanite Pave',
    image:
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=92',
    description:
      'A heavier Cuban profile with icy pave detail and a clean black-tie-meets-block fit.',
    drop: 'Block Black Tie',
    finish: 'High-polish curb links',
    certificateId: 'GRA-IV-033',
    certificateDate: 'May 2026',
    carat: '22 ct total weight',
    cut: 'Micro pave rounds',
    clarity: 'VVS simulated clarity',
    specs: ['12mm curb profile', 'Secure lock clasp', 'Heavy drape'],
    tags: ['gra certified', 'cuban', 'chain', 'streetwear'],
  },
  {
    id: 'halo-stud-set',
    name: 'Halo Stud Set',
    category: 'earrings',
    price: 190,
    stock: 12,
    certification: 'GRA Certified',
    stone: 'Round Moissanite',
    image:
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=92',
    description:
      'Compact halo studs with maximum flash, built for a clean everyday rotation.',
    drop: 'Core Essentials',
    finish: 'White gold basket',
    certificateId: 'GRA-IV-042',
    certificateDate: 'May 2026',
    carat: '1.5 ct each ear',
    cut: 'Round halo',
    clarity: 'D color moissanite',
    specs: ['Push-back closure', 'Round halo face', 'Matched pair'],
    tags: ['gra certified', 'studs', 'earrings', 'daily'],
  },
  {
    id: 'black-ice-watch',
    name: 'Black Ice Watch',
    category: 'watches',
    price: 890,
    stock: 2,
    certification: 'GRA Certified',
    stone: 'Moissanite Bezel',
    image:
      'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=1200&q=92',
    description:
      'Black dial, cold bezel, and a polished bracelet that reads quiet until it catches light.',
    drop: 'After Dark',
    finish: 'Black dial, polished bracelet',
    certificateId: 'GRA-IV-057',
    certificateDate: 'May 2026',
    carat: 'Bezel-set moissanite',
    cut: 'Round bezel set',
    clarity: 'VVS simulated clarity',
    specs: ['Moissanite bezel', 'Quartz movement', 'Statement weight'],
    tags: ['gra certified', 'watch', 'black ice', 'statement'],
  },
]
